### ISSUE TITLE
peer dependency msw has a new version msw@^1.0.1

### ISSUE THREAD

**Issue by ibqn** [iodigital-com/vite-plugin-msw#3]
Hello, I have noticed, that vite-plugin-msw has a peer dependency requirement for msw@^0.47.4

 WARN  Issues with peer dependencies found
.
└─┬ @iodigital/vite-plugin-msw 0.3.0
  └── ✕ unmet peer msw@^0.47.4: found 1.0.1
  
  That would be great if it can be lifted up.

**Comment by mrtnvh** [comment]
Pushed msw peer-dep minimum version to v1. Release in `@iodigital/vite-plugin-msw` v1.0.0.
